{{- if .Values.management.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-management
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.management.service.type }}
  ports:
    - port: {{ .Values.management.service.port }}
      targetPort: {{ .Values.management.service.name }}
      protocol: TCP
      name: {{ .Values.management.service.name }}
    - port: {{ .Values.management.service.grpcPort }}
      targetPort: {{ .Values.management.service.name }}
      protocol: TCP
      appProtocol: kubernetes.io/h2c
      name: {{ .Values.management.service.grpcName }}
    - port: {{ .Values.management.service.wsPort }}
      targetPort: {{ .Values.management.service.name }}
      protocol: TCP
      appProtocol: kubernetes.io/ws
      name: {{ .Values.management.service.wsName }}
    {{- if .Values.management.metrics.enabled }}
    - port: {{ .Values.management.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "netbird.management.selectorLabels" . | nindent 4 }}
{{- end }}
